/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */

/**
 *
 * @author Nombre <>
 */
public class Paginas {
    

    public static final String html_noEncontrado = "<html><head><title>Error 404</title><link rel=icon href=data:,/></head><body>"
        + "<h1>404 Página No Encontrada</h1>"
        + "<p>La página solicitada no existe.</p>"
        + "</body></html>";
    
    public static final String html_reservas = "<!DOCTYPE html>"
        + "<html lang='es'>"
        + "<head>"
        + "<meta charset='UTF-8'>"
        + "<meta name='viewport' content='width=device-width, initial-scale=1.0'>"
        + "<title>Hotel & Reservas</title>"
        + "<style>"
        + "body {"
        + "font-family: 'Arial', sans-serif;"
        + "background-color: #eef2f3;"
        + "margin: 0; padding: 0;"
        + "}"
        + "header {"
        + "background-color: #4CAF50;"
        + "color: white;"
        + "text-align: center;"
        + "padding: 20px 0;"
        + "}"
        + ".container {"
        + "max-width: 450px;"
        + "margin: 40px auto;"
        + "background-color: white;"
        + "padding: 25px;"
        + "box-shadow: 0 0 12px rgba(0,0,0,0.1);"
        + "border-radius: 8px;"
        + "}"
        + "label {"
        + "display: block;"
        + "font-weight: bold;"
        + "margin-top: 10px;"
        + "}"
        + "select, input[type='number'] {"
        + "width: 100%;"
        + "padding: 10px;"
        + "margin-top: 5px;"
        + "margin-bottom: 15px;"
        + "border: 1px solid #ccc;"
        + "border-radius: 4px;"
        + "font-size: 15px;"
        + "}"
        + "button {"
        + "width: 100%;"
        + "padding: 12px;"
        + "background-color: #4CAF50;"
        + "color: white;"
        + "font-size: 16px;"
        + "border: none;"
        + "border-radius: 4px;"
        + "cursor: pointer;"
        + "transition: background-color 0.3s ease;"
        + "}"
        + "button:hover {"
        + "background-color: #45a049;"
        + "}"
        + "</style>"
        + "</head>"
        + "<body>"
        + "<header>"
        + "<h1>Hotel PelHilos a la mar</h1>"
        + "<p>Registro de reservas por d�a</p>"
        + "</header>"
        + "<div class='container'>"
        + "<form action='/' method='POST'>"
        + "<label for='dia'>Día de la semana:</label>"
        + "<select id='dia' name='dia'>"
        + "<option value='lunes'>Lunes</option>"
        + "<option value='martes'>Martes</option>"
        + "<option value='miercoles'>Miércoles</option>"
        + "<option value='jueves'>Jueves</option>"
        + "<option value='viernes'>Viernes</option>"
        + "<option value='sabado'>Sábado</option>"
        + "<option value='domingo'>Domingo</option>"
        + "</select>"
        + "<label for='cantidad'>Número de habitaciones:</label>"
        + "<input type='number' id='cantidad' name='cantidad' min='1' required autofocus>"
        + "<button type='submit'>Reservar</button>"
        + "</form>"
        + "</div>"
        + "</body>"
        + "</html>";

}
